# Generated by Django 4.2.7 on 2026-04-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='audiobooks/', verbose_name='音频文件')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('novel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audiobook', to='novels.novel')),
            ],
            options={
                'verbose_name': '有声书',
                'verbose_name_plural': '有声书',
                'ordering': ['-created_at'],
            },
        ),
    ]
