# Generated by Django 4.2.7 on 2026-04-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('role_type', models.CharField(choices=[('protagonist', '主角'), ('supporting', '配角'), ('antagonist', '反派'), ('minor', '次要人物')], default='supporting', max_length=20, verbose_name='角色类型')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('age', models.CharField(choices=[('young', '青年'), ('middle-aged', '中年'), ('elderly', '老年'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='年龄')),
                ('personality', models.CharField(blank=True, max_length=200, verbose_name='性格特征')),
                ('speaking_style', models.CharField(blank=True, max_length=100, verbose_name='说话风格')),
                ('temperament', models.CharField(blank=True, max_length=100, verbose_name='气质类型')),
                ('catchphrase', models.CharField(blank=True, max_length=200, verbose_name='口头禅')),
                ('voice_id', models.CharField(default='Chinese_Male_Neutral', max_length=100, verbose_name='音色ID')),
                ('default_emotion', models.CharField(default='neutral', max_length=50, verbose_name='默认情感')),
                ('importance_score', models.IntegerField(default=50, verbose_name='重要程度')),
                ('auto_detected', models.BooleanField(default=True, verbose_name='AI自动识别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.AddField(
            model_name='novel',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True, verbose_name='AI分析结果'),
        ),
        migrations.AddField(
            model_name='novel',
            name='genre',
            field=models.CharField(choices=[('fantasy', '玄幻'), ('urban', '都市'), ('xianxia', '仙侠'), ('wuxia', '武侠'), ('romance', '言情'), ('scifi', '科幻'), ('mystery', '悬疑'), ('historical', '历史'), ('other', '其他')], default='other', max_length=20, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='novel',
            name='setting',
            field=models.CharField(blank=True, max_length=100, verbose_name='背景设定'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('analyzing', 'AI分析中'), ('processing', '音频生成中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(default=1, verbose_name='章节号')),
                ('scene_id', models.IntegerField(default=1, verbose_name='场景序号')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='场景地点')),
                ('time_of_day', models.CharField(blank=True, max_length=50, verbose_name='时间')),
                ('season', models.CharField(blank=True, max_length=50, verbose_name='季节')),
                ('weather', models.CharField(blank=True, max_length=50, verbose_name='天气')),
                ('atmosphere', models.TextField(blank=True, verbose_name='氛围描述')),
                ('mood', models.CharField(choices=[('happy', '欢快'), ('tense', '紧张'), ('sad', '悲伤'), ('romantic', '浪漫'), ('mysterious', '神秘'), ('calm', '平静'), ('excited', '激动'), ('horror', '恐怖')], default='calm', max_length=50, verbose_name='情绪基调')),
                ('suggested_bgm', models.CharField(blank=True, max_length=500, verbose_name='推荐BGM描述')),
                ('suggested_sfx', models.JSONField(blank=True, null=True, verbose_name='推荐音效')),
                ('bgm_volume', models.FloatField(default=0.3, verbose_name='BGM音量')),
                ('sfx_volume', models.FloatField(default=0.5, verbose_name='音效音量')),
                ('narration_text', models.TextField(blank=True, verbose_name='叙述段落')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='novels.novel')),
            ],
            options={
                'verbose_name': '场景',
                'verbose_name_plural': '场景',
                'ordering': ['novel', 'chapter_number', 'scene_id'],
            },
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='对话内容')),
                ('emotion', models.CharField(choices=[('neutral', '中性'), ('happy', '开心'), ('sad', '悲伤'), ('angry', '愤怒'), ('fearful', '恐惧'), ('surprised', '惊讶'), ('tense', '紧张'), ('excited', '激动'), ('romantic', '浪漫'), ('mysterious', '神秘')], default='neutral', max_length=20, verbose_name='情感')),
                ('volume', models.CharField(choices=[('normal', '正常'), ('loud', '大声'), ('whisper', '低声'), ('calling', '喊叫')], default='normal', max_length=20, verbose_name='音量')),
                ('speed', models.CharField(choices=[('slow', '慢速'), ('normal', '正常'), ('fast', '快速')], default='normal', max_length=20, verbose_name='语速')),
                ('special_effects', models.CharField(blank=True, max_length=200, verbose_name='特殊效果')),
                ('order', models.IntegerField(default=0, verbose_name='顺序')),
                ('audio_path', models.CharField(blank=True, max_length=500, verbose_name='音频路径')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='novels.character')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='novels.scene')),
            ],
            options={
                'verbose_name': '对话',
                'verbose_name_plural': '对话',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='novels.novel'),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('novel', 'name')},
        ),
    ]
