# Generated by Django 5.2.13 on 2026-04-27 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='逝世日期')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='照片')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='family.member', verbose_name='父亲')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='family.member', verbose_name='母亲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '家庭成员',
                'verbose_name_plural': '家庭成员',
                'db_table': 'members',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('father', '父亲'), ('mother', '母亲'), ('spouse', '配偶'), ('child', '子女'), ('sibling', '兄弟姐妹')], max_length=20, verbose_name='关系类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='family.member')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='family.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '家庭关系',
                'verbose_name_plural': '家庭关系',
                'db_table': 'relations',
                'unique_together': {('from_member', 'to_member', 'relation_type')},
            },
        ),
    ]
